from lexer import lexer
from parser import parser

def testar_codigo(fortran_code):
    print(f"---Testing code---\n{fortran_code}\n------")
    print("Tokens:")
    lexer.input(fortran_code)
    for token in lexer:
        print(token)

    print("\nSynthatic tree generated by parser:")
    result = parser.parse(fortran_code)
    print(result)
    print("\n")


code1 = """PROGRAM TESTE
INTEGER N
END"""
testar_codigo(code1)


code2 = """PROGRAM TESTE2
INTEGER I, NUMS(5), SOMA
END"""
testar_codigo(code2)
