from lexer import lexer
from parser import parser
from semantic import analyze_semantics
from codegen import generate_code

def testar_codigo(fortran_code):
    print(f"---Testing code---\n{fortran_code}\n------")
    print("Tokens:")
    lexer.input(fortran_code)
    for token in lexer:
        print(token)

    print("\nSynthatic tree generated by parser:")
    result = parser.parse(fortran_code)
    if result:
        print("\n--- Syntatic analysis ---\n")
        analyze_semantics(result)
    print(result)
    print("\n")

def compile_code(code):
    syn_tree = parser.parse(code)
    if syn_tree:
        analyze_semantics(syn_tree)
        return generate_code(syn_tree)


simple_test_code = """
PROGRAM MAT
INTEGER A, B, C
A = 10
B = 5
C = A + B * 2
END
"""

print("Compiling Code")
compiled = compile_code(simple_test_code)

print("--- Code Start ---")
print(compiled)
print("--- Code End ---")

code_if_test = """PROGRAM TESTEIF
INTEGER QUOT, VAL
QUOT = 5
VAL = 0
20 IF (QUOT .GT. 0) THEN
    VAL = VAL + 1
    QUOT = QUOT - 1
    GOTO 20
ENDIF
END"""

compiled = compile_code(code_if_test)

print("--- Code Start ---")
print(compiled)
print("--- Code End ---")

