from lexer import lexer
from parser import parser

def testar_codigo(fortran_code):
    print(f"---Testing code---\n{fortran_code}\n------")
    print("Tokens:")
    lexer.input(fortran_code)
    for token in lexer:
        print(token)

    print("\nSynthatic tree generated by parser:")
    result = parser.parse(fortran_code)
    print(result)
    print("\n")


code1 = """PROGRAM TESTE
INTEGER N
END"""
testar_codigo(code1)


code2 = """PROGRAM TESTE2
INTEGER I, NUMS(5), SOMA
END"""
testar_codigo(code2)

code_assign = """PROGRAM TESTE3
FAT = 1
NUMS(I) = 5
END"""
testar_codigo(code_assign)

code_math = """PROGRAM MATH
FAT = FAT * I
SOMA = 10 + 5 * 2
END"""
testar_codigo(code_math)

code_rel = """PROGRAM RELACIONAL
VER1 = A .GE. 0
VER2 = I .LE. NUM / 2
END"""
testar_codigo(code_rel)


code_logic = """PROGRAM LOGIC
ISNUMBER = .TRUE.
ISLEPRIM = I .LE. (NUM/2) .AND. ISPRIM
END"""
testar_codigo(code_logic)


code_if = """PROGRAM TESTEIF
IF (NUM .GT. 0) THEN
    ISPRIM = .TRUE.
ELSE
    ISPRIM = .FALSE.
ENDIF

IF (ISPRIM) THEN
    SOMA = 1
ENDIF
END"""

testar_codigo(code_if)


code_do = """PROGRAM DO_LOOP
DO 10 I = 1, N
    FAT = FAT * I
10 CONTINUE
END"""
testar_codigo(code_do)


code_print_read = """PROGRAM PRINTREAD
PRINT *, 'Numero a'
READ *, N
READ *, NUMS(I)
PRINT *, 'Fatorial de', N, ':', FAT
END"""

testar_codigo(code_print_read)


codigo_funcoes = """PROGRAM PRINCIPAL
RESULT = CONVRT(NUM, BASE)
END

INTEGER FUNCTION CONVRT(N, B)
VAL = N + B
CONVRT = VAL
RETURN
END"""

testar_codigo(codigo_funcoes)
