
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA CONTINUE DIVIDE DO ELSE END ENDIF EQUALS FALSE GOTO ID IF INTEGER LOGICAL LPAREN MINUS NUMBER PLUS PRINT PROGRAM READ REAL RPAREN STRING THEN TIMES TRUEprogram : PROGRAM ID statements ENDstatements : statement\n| statements statementstatement : declarationvar_dec : ID\n| ID LPAREN NUMBER RPARENid_list : var_dec\n| id_list COMMA var_dectype : INTEGER\n| REAL\n| LOGICALdeclaration : type id_list'
    
_lr_action_items = {'PROGRAM':([0,],[2,]),'$end':([1,11,],[0,-1,]),'ID':([2,7,8,9,10,16,],[3,15,-9,-10,-11,15,]),'INTEGER':([3,4,5,6,12,13,14,15,18,20,],[8,8,-2,-4,-3,-12,-7,-5,-8,-6,]),'REAL':([3,4,5,6,12,13,14,15,18,20,],[9,9,-2,-4,-3,-12,-7,-5,-8,-6,]),'LOGICAL':([3,4,5,6,12,13,14,15,18,20,],[10,10,-2,-4,-3,-12,-7,-5,-8,-6,]),'END':([4,5,6,12,13,14,15,18,20,],[11,-2,-4,-3,-12,-7,-5,-8,-6,]),'COMMA':([13,14,15,18,20,],[16,-7,-5,-8,-6,]),'LPAREN':([15,],[17,]),'NUMBER':([17,],[19,]),'RPAREN':([19,],[20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([3,],[4,]),'statement':([3,4,],[5,12,]),'declaration':([3,4,],[6,6,]),'type':([3,4,],[7,7,]),'id_list':([7,],[13,]),'var_dec':([7,16,],[14,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PROGRAM ID statements END','program',4,'p_program','parser.py',5),
  ('statements -> statement','statements',1,'p_statements','parser.py',9),
  ('statements -> statements statement','statements',2,'p_statements','parser.py',10),
  ('statement -> declaration','statement',1,'p_statement','parser.py',19),
  ('var_dec -> ID','var_dec',1,'p_var_dec','parser.py',23),
  ('var_dec -> ID LPAREN NUMBER RPAREN','var_dec',4,'p_var_dec','parser.py',24),
  ('id_list -> var_dec','id_list',1,'p_id_list','parser.py',31),
  ('id_list -> id_list COMMA var_dec','id_list',3,'p_id_list','parser.py',32),
  ('type -> INTEGER','type',1,'p_type','parser.py',42),
  ('type -> REAL','type',1,'p_type','parser.py',43),
  ('type -> LOGICAL','type',1,'p_type','parser.py',44),
  ('declaration -> type id_list','declaration',2,'p_declaration','parser.py',51),
]
