PROGRAM DCE
PRINT *, 'INICIO'
IF (.TRUE.) THEN
PRINT *, 'TESTE 1: SEMPRE VERDADEIRO (IF)'
ENDIF
IF (.FALSE.) THEN
PRINT *, 'TESTE 2: CODIGO MORTO (NAO APARECE)'
ELSE
PRINT *, 'TESTE 2: ELSE'
ENDIF
IF (10 .GT. 5) THEN
PRINT *, 'TESTE 3: 10 > 5 CONSTANT FOLDING E DCE'
ENDIF
PRINT *, 'FIM'
END
